use_frameworks!

platform :ios, '13.0'

target 'SwiftUIWheelPicker_Example' do
  pod 'SwiftUIWheelPicker', :path => '../'

  target 'SwiftUIWheelPicker_Tests' do
    inherit! :search_paths

    
  end
end
